-- virtual warehouses: etl, query
USE ROLE SYSADMIN;

CREATE WAREHOUSE ETL
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    COMMENT = 'A computing resource for dbt to run ETL';

--Question to identify if this is needed
-- CREATE WAREHOUSE QUERY
-- WITH
--     WAREHOUSE_SIZE = 'XSMALL'
--     AUTO_SUSPEND = 60
--     AUTO_RESUME = TRUE
--     COMMENT = 'A computing resource for dbt to run ETL';

-- databases and schemas
CREATE DATABASE IF NOT EXISTS TVSHOW;
CREATE SCHEMA IF NOT EXISTS TVSHOW.SOURCE; --raw
CREATE SCHEMA IF NOT EXISTS TVSHOW.MODEL; --silver
CREATE SCHEMA IF NOT EXISTS TVSHOW.EXPOSE; --gold
CREATE SCHEMA IF NOT EXISTS TVSHOW.UTIL;

-- roles and users
USE ROLE USERADMIN;

CREATE ROLE IF NOT EXISTS DBT_RW;
CREATE USER IF NOT EXISTS dbt
    PASSWORD='project2tvshows'
    LOGIN_NAME='dbt'
    MUST_CHANGE_PASSWORD=FALSE
    DEFAULT_WAREHOUSE='ETL'
    DEFAULT_ROLE='DBT_RW'
    DEFAULT_NAMESPACE='TVSHOW.SOURCE'
    COMMENT='A dbt user used for ETL';

-- set up permissions
USE ROLE SECURITYADMIN;

GRANT ROLE DBT_RW TO USER dbt;
-- dbt_rw account level
GRANT USAGE ON WAREHOUSE ETL TO ROLE DBT_RW;
-- dbt_rw schema level
GRANT ALL ON ALL SCHEMAS IN DATABASE TVSHOW TO ROLE DBT_RW;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE TVSHOW TO ROLE DBT_RW;
-- dbt_rw object level
GRANT ALL ON ALL TABLES IN SCHEMA TVSHOW.SOURCE TO ROLE DBT_RW;
GRANT ALL ON FUTURE TABLES IN SCHEMA TVSHOW.SOURCE TO ROLE DBT_RW;
GRANT ALL ON ALL TABLES IN SCHEMA TVSHOW.MODEL TO ROLE DBT_RW;
GRANT ALL ON FUTURE TABLES IN SCHEMA TVSHOW.MODEL TO ROLE DBT_RW;
GRANT ALL ON ALL VIEWS IN SCHEMA TVSHOW.EXPOSE TO ROLE DBT_RW;
GRANT ALL ON FUTURE VIEWS IN SCHEMA TVSHOW.EXPOSE TO ROLE DBT_RW;
